In [15]:
import pandas as pd

In [30]:
df = pd.read_csv('data.csv')
df.head()

       country  year  scenario  value
0  Afghanistan  2015  SSP1-2.6  0.000
1  Afghanistan  2016  SSP1-2.6  0.497
2  Afghanistan  2017  SSP1-2.6  1.809
3  Afghanistan  2018  SSP1-2.6  0.397
4  Afghanistan  2019  SSP1-2.6 -0.545

In [32]:
df = df[df['country'] != 'Glabal']

In [33]:
avg = df.groupby(['year', 'scenario'])['value'].mean().reset_index()
avg['country'] = 'Global'
avg = avg[['country', 'year', 'scenario', 'value']]
avg

    country  year  scenario     value
0    Global  2015  SSP1-2.6  0.000000
1    Global  2015  SSP2-4.5  0.000000
2    Global  2015  SSP3-7.0  0.000000
3    Global  2015  SSP5-8.5  0.000000
4    Global  2016  SSP1-2.6 -0.060150
..      ...   ...       ...       ...
339  Global  2099  SSP5-8.5  7.273836
340  Global  2100  SSP1-2.6  1.611771
341  Global  2100  SSP2-4.5  2.923900
342  Global  2100  SSP3-7.0  5.633057
343  Global  2100  SSP5-8.5  7.213264

[344 rows x 4 columns]

In [34]:
df = pd.concat([df, avg]).reset_index(drop=True)

In [35]:
df.to_csv('data.csv', index=False)